# Generated by Django 5.1.3 on 2024-11-13 14:40

import django.db.models.deletion
import taggit.managers
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('taggit', '0006_rename_taggeditem_content_type_object_id_taggit_tagg_content_8fc721_idx'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogComponent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_type', models.CharField(max_length=225)),
                ('file_content', models.FileField(blank=True, null=True, upload_to='file_content')),
                ('text_content', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='BlogNode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('next_node', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='next_node_block', to='blog.blogcomponent')),
                ('priv_node', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='previous_node_block', to='blog.blogcomponent')),
            ],
        ),
        migrations.CreateModel(
            name='BlogTree',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blog_title', models.CharField(max_length=225)),
                ('blog_genre', models.CharField(max_length=225)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('blog_content', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='blog.blognode')),
                ('blog_tags', taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags')),
            ],
        ),
    ]
