# Generated by Django 5.1.3 on 2024-11-16 17:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogtree',
            name='blog_content',
        ),
        migrations.RemoveField(
            model_name='blogtree',
            name='blog_genre',
        ),
        migrations.AddField(
            model_name='blogcomponent',
            name='next_node',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='next_node_block', to='blog.blogcomponent'),
        ),
        migrations.AddField(
            model_name='blogcomponent',
            name='priv_node',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='previous_node_block', to='blog.blogcomponent'),
        ),
        migrations.AddField(
            model_name='blogtree',
            name='blog_owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='blogtree',
            name='blog_root',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='blog.blogcomponent'),
        ),
        migrations.AddField(
            model_name='blogtree',
            name='isPublished',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='BlogNode',
        ),
    ]
