# Generated by Django 5.1.3 on 2024-11-16 18:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_remove_blogtree_blog_content_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogcomponent',
            name='priv_node',
        ),
    ]
