# Generated by Django 5.0 on 2024-06-28 13:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_testimonymodel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testimonymodel',
            name='user',
        ),
    ]
