# Generated by Django 5.0 on 2024-07-06 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_alter_authusermodel_managers_and_more'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='authusermodel',
            managers=[
            ],
        ),
        migrations.AlterField(
            model_name='authusermodel',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
