# Generated by Django 5.0 on 2024-07-16 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_alter_authusermodel_managers_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='testimonymodel',
            name='name',
            field=models.CharField(default=None, max_length=200),
        ),
    ]
