# Generated by Django 5.0 on 2024-07-19 18:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_testimonymodel_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='testimonymodel',
            options={'ordering': ('approved',)},
        ),
    ]
