# Generated by Django 5.0 on 2024-08-01 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_alter_testimonymodel_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testimonymodel',
            name='image',
        ),
        migrations.AddField(
            model_name='testimonymodel',
            name='email',
            field=models.EmailField(default='demo@demo.com', max_length=254),
        ),
    ]
